version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=carlos
      - POSTGRES_PASSWORD=docker1
      - POSTGRES_DB=shortlinks

  redis:
    image: bitnami/redis:latest
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=docker1